// Code generated by go-swagger; DO NOT EDIT.

package reviewer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// AddNewReviewerOKCode is the HTTP code returned for type AddNewReviewerOK
const AddNewReviewerOKCode int = 200

/*AddNewReviewerOK OK

swagger:response addNewReviewerOK
*/
type AddNewReviewerOK struct {
}

// NewAddNewReviewerOK creates AddNewReviewerOK with default headers values
func NewAddNewReviewerOK() *AddNewReviewerOK {

	return &AddNewReviewerOK{}
}

// WriteResponse to the client
func (o *AddNewReviewerOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// AddNewReviewerBadRequestCode is the HTTP code returned for type AddNewReviewerBadRequest
const AddNewReviewerBadRequestCode int = 400

/*AddNewReviewerBadRequest invalid input

swagger:response addNewReviewerBadRequest
*/
type AddNewReviewerBadRequest struct {
}

// NewAddNewReviewerBadRequest creates AddNewReviewerBadRequest with default headers values
func NewAddNewReviewerBadRequest() *AddNewReviewerBadRequest {

	return &AddNewReviewerBadRequest{}
}

// WriteResponse to the client
func (o *AddNewReviewerBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}
