// Code generated by go-swagger; DO NOT EDIT.

package reviewer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	"github.com/LicaSterian/swagger-test/models"
)

// NewAddNewReviewerParams creates a new AddNewReviewerParams object
// no default values defined in spec.
func NewAddNewReviewerParams() AddNewReviewerParams {

	return AddNewReviewerParams{}
}

// AddNewReviewerParams contains all the bound params for the add new reviewer operation
// typically these are obtained from a http.Request
//
// swagger:parameters addNewReviewer
type AddNewReviewerParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: body
	*/
	Reviewer *models.Reviewer
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewAddNewReviewerParams() beforehand.
func (o *AddNewReviewerParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.Reviewer
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("reviewer", "body"))
			} else {
				res = append(res, errors.NewParseError("reviewer", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Reviewer = &body
			}
		}
	} else {
		res = append(res, errors.Required("reviewer", "body"))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
