// Code generated by go-swagger; DO NOT EDIT.

package reviewer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteReviewerNoContentCode is the HTTP code returned for type DeleteReviewerNoContent
const DeleteReviewerNoContentCode int = 204

/*DeleteReviewerNoContent Deleted

swagger:response deleteReviewerNoContent
*/
type DeleteReviewerNoContent struct {
}

// NewDeleteReviewerNoContent creates DeleteReviewerNoContent with default headers values
func NewDeleteReviewerNoContent() *DeleteReviewerNoContent {

	return &DeleteReviewerNoContent{}
}

// WriteResponse to the client
func (o *DeleteReviewerNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// DeleteReviewerBadRequestCode is the HTTP code returned for type DeleteReviewerBadRequest
const DeleteReviewerBadRequestCode int = 400

/*DeleteReviewerBadRequest invalid input

swagger:response deleteReviewerBadRequest
*/
type DeleteReviewerBadRequest struct {
}

// NewDeleteReviewerBadRequest creates DeleteReviewerBadRequest with default headers values
func NewDeleteReviewerBadRequest() *DeleteReviewerBadRequest {

	return &DeleteReviewerBadRequest{}
}

// WriteResponse to the client
func (o *DeleteReviewerBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// DeleteReviewerNotFoundCode is the HTTP code returned for type DeleteReviewerNotFound
const DeleteReviewerNotFoundCode int = 404

/*DeleteReviewerNotFound reviewerId not Found

swagger:response deleteReviewerNotFound
*/
type DeleteReviewerNotFound struct {
}

// NewDeleteReviewerNotFound creates DeleteReviewerNotFound with default headers values
func NewDeleteReviewerNotFound() *DeleteReviewerNotFound {

	return &DeleteReviewerNotFound{}
}

// WriteResponse to the client
func (o *DeleteReviewerNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
