// Code generated by go-swagger; DO NOT EDIT.

package reviewer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetAllReviewersHandlerFunc turns a function with the right signature into a get all reviewers handler
type GetAllReviewersHandlerFunc func(GetAllReviewersParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetAllReviewersHandlerFunc) Handle(params GetAllReviewersParams) middleware.Responder {
	return fn(params)
}

// GetAllReviewersHandler interface for that can handle valid get all reviewers params
type GetAllReviewersHandler interface {
	Handle(GetAllReviewersParams) middleware.Responder
}

// NewGetAllReviewers creates a new http.Handler for the get all reviewers operation
func NewGetAllReviewers(ctx *middleware.Context, handler GetAllReviewersHandler) *GetAllReviewers {
	return &GetAllReviewers{Context: ctx, Handler: handler}
}

/*GetAllReviewers swagger:route GET /reviewers reviewer getAllReviewers

get all reviewers

return all reviewers


*/
type GetAllReviewers struct {
	Context *middleware.Context
	Handler GetAllReviewersHandler
}

func (o *GetAllReviewers) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetAllReviewersParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
