// Code generated by go-swagger; DO NOT EDIT.

package reviewer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// UpdateReviewerHandlerFunc turns a function with the right signature into a update reviewer handler
type UpdateReviewerHandlerFunc func(UpdateReviewerParams) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdateReviewerHandlerFunc) Handle(params UpdateReviewerParams) middleware.Responder {
	return fn(params)
}

// UpdateReviewerHandler interface for that can handle valid update reviewer params
type UpdateReviewerHandler interface {
	Handle(UpdateReviewerParams) middleware.Responder
}

// NewUpdateReviewer creates a new http.Handler for the update reviewer operation
func NewUpdateReviewer(ctx *middleware.Context, handler UpdateReviewerHandler) *UpdateReviewer {
	return &UpdateReviewer{Context: ctx, Handler: handler}
}

/*UpdateReviewer swagger:route PUT /reviewer/{id} reviewer updateReviewer

update a reviewer by reviewer id

*/
type UpdateReviewer struct {
	Context *middleware.Context
	Handler UpdateReviewerHandler
}

func (o *UpdateReviewer) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewUpdateReviewerParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
