// Code generated by go-swagger; DO NOT EDIT.

package reviewer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// UpdateReviewerOKCode is the HTTP code returned for type UpdateReviewerOK
const UpdateReviewerOKCode int = 200

/*UpdateReviewerOK Updated

swagger:response updateReviewerOK
*/
type UpdateReviewerOK struct {
}

// NewUpdateReviewerOK creates UpdateReviewerOK with default headers values
func NewUpdateReviewerOK() *UpdateReviewerOK {

	return &UpdateReviewerOK{}
}

// WriteResponse to the client
func (o *UpdateReviewerOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// UpdateReviewerBadRequestCode is the HTTP code returned for type UpdateReviewerBadRequest
const UpdateReviewerBadRequestCode int = 400

/*UpdateReviewerBadRequest invalid input

swagger:response updateReviewerBadRequest
*/
type UpdateReviewerBadRequest struct {
}

// NewUpdateReviewerBadRequest creates UpdateReviewerBadRequest with default headers values
func NewUpdateReviewerBadRequest() *UpdateReviewerBadRequest {

	return &UpdateReviewerBadRequest{}
}

// WriteResponse to the client
func (o *UpdateReviewerBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// UpdateReviewerNotFoundCode is the HTTP code returned for type UpdateReviewerNotFound
const UpdateReviewerNotFoundCode int = 404

/*UpdateReviewerNotFound reviewerId not Found

swagger:response updateReviewerNotFound
*/
type UpdateReviewerNotFound struct {
}

// NewUpdateReviewerNotFound creates UpdateReviewerNotFound with default headers values
func NewUpdateReviewerNotFound() *UpdateReviewerNotFound {

	return &UpdateReviewerNotFound{}
}

// WriteResponse to the client
func (o *UpdateReviewerNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
