// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Simple BookStore API
//
//  This is a simple API
//  Schemes:
//    http
//  Host: localhost:8080
//  BasePath: /api/v1
//  Version: 1.0.0
//  License: Apache 2.0 http://www.apache.org/licenses/LICENSE-2.0.html
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
