// Code generated by go-swagger; DO NOT EDIT.

package book

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// AddNewbookOKCode is the HTTP code returned for type AddNewbookOK
const AddNewbookOKCode int = 200

/*AddNewbookOK OK

swagger:response addNewbookOK
*/
type AddNewbookOK struct {
}

// NewAddNewbookOK creates AddNewbookOK with default headers values
func NewAddNewbookOK() *AddNewbookOK {

	return &AddNewbookOK{}
}

// WriteResponse to the client
func (o *AddNewbookOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// AddNewbookBadRequestCode is the HTTP code returned for type AddNewbookBadRequest
const AddNewbookBadRequestCode int = 400

/*AddNewbookBadRequest invalid input

swagger:response addNewbookBadRequest
*/
type AddNewbookBadRequest struct {
}

// NewAddNewbookBadRequest creates AddNewbookBadRequest with default headers values
func NewAddNewbookBadRequest() *AddNewbookBadRequest {

	return &AddNewbookBadRequest{}
}

// WriteResponse to the client
func (o *AddNewbookBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}
