// Code generated by go-swagger; DO NOT EDIT.

package book

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/LicaSterian/swagger-test/models"
)

// AddNewbookOKCode is the HTTP code returned for type AddNewbookOK
const AddNewbookOKCode int = 200

/*AddNewbookOK OK

swagger:response addNewbookOK
*/
type AddNewbookOK struct {

	/*
	  In: Body
	*/
	Payload *models.Book `json:"body,omitempty"`
}

// NewAddNewbookOK creates AddNewbookOK with default headers values
func NewAddNewbookOK() *AddNewbookOK {

	return &AddNewbookOK{}
}

// WithPayload adds the payload to the add newbook o k response
func (o *AddNewbookOK) WithPayload(payload *models.Book) *AddNewbookOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add newbook o k response
func (o *AddNewbookOK) SetPayload(payload *models.Book) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddNewbookOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// AddNewbookBadRequestCode is the HTTP code returned for type AddNewbookBadRequest
const AddNewbookBadRequestCode int = 400

/*AddNewbookBadRequest invalid input

swagger:response addNewbookBadRequest
*/
type AddNewbookBadRequest struct {
}

// NewAddNewbookBadRequest creates AddNewbookBadRequest with default headers values
func NewAddNewbookBadRequest() *AddNewbookBadRequest {

	return &AddNewbookBadRequest{}
}

// WriteResponse to the client
func (o *AddNewbookBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}
