// Code generated by go-swagger; DO NOT EDIT.

package book

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteBookNoContentCode is the HTTP code returned for type DeleteBookNoContent
const DeleteBookNoContentCode int = 204

/*DeleteBookNoContent Deleted

swagger:response deleteBookNoContent
*/
type DeleteBookNoContent struct {
}

// NewDeleteBookNoContent creates DeleteBookNoContent with default headers values
func NewDeleteBookNoContent() *DeleteBookNoContent {

	return &DeleteBookNoContent{}
}

// WriteResponse to the client
func (o *DeleteBookNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// DeleteBookBadRequestCode is the HTTP code returned for type DeleteBookBadRequest
const DeleteBookBadRequestCode int = 400

/*DeleteBookBadRequest invalid input

swagger:response deleteBookBadRequest
*/
type DeleteBookBadRequest struct {
}

// NewDeleteBookBadRequest creates DeleteBookBadRequest with default headers values
func NewDeleteBookBadRequest() *DeleteBookBadRequest {

	return &DeleteBookBadRequest{}
}

// WriteResponse to the client
func (o *DeleteBookBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// DeleteBookNotFoundCode is the HTTP code returned for type DeleteBookNotFound
const DeleteBookNotFoundCode int = 404

/*DeleteBookNotFound bookId not Found

swagger:response deleteBookNotFound
*/
type DeleteBookNotFound struct {
}

// NewDeleteBookNotFound creates DeleteBookNotFound with default headers values
func NewDeleteBookNotFound() *DeleteBookNotFound {

	return &DeleteBookNotFound{}
}

// WriteResponse to the client
func (o *DeleteBookNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
