// Code generated by go-swagger; DO NOT EDIT.

package book

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/LicaSterian/swagger-test/models"
)

// GetAllBooksOKCode is the HTTP code returned for type GetAllBooksOK
const GetAllBooksOKCode int = 200

/*GetAllBooksOK list of Books

swagger:response getAllBooksOK
*/
type GetAllBooksOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Book `json:"body,omitempty"`
}

// NewGetAllBooksOK creates GetAllBooksOK with default headers values
func NewGetAllBooksOK() *GetAllBooksOK {

	return &GetAllBooksOK{}
}

// WithPayload adds the payload to the get all books o k response
func (o *GetAllBooksOK) WithPayload(payload []*models.Book) *GetAllBooksOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get all books o k response
func (o *GetAllBooksOK) SetPayload(payload []*models.Book) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAllBooksOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Book, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetAllBooksBadRequestCode is the HTTP code returned for type GetAllBooksBadRequest
const GetAllBooksBadRequestCode int = 400

/*GetAllBooksBadRequest bad input parameter

swagger:response getAllBooksBadRequest
*/
type GetAllBooksBadRequest struct {
}

// NewGetAllBooksBadRequest creates GetAllBooksBadRequest with default headers values
func NewGetAllBooksBadRequest() *GetAllBooksBadRequest {

	return &GetAllBooksBadRequest{}
}

// WriteResponse to the client
func (o *GetAllBooksBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}
