// Code generated by go-swagger; DO NOT EDIT.

package book

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetAllBooksHandlerFunc turns a function with the right signature into a get all books handler
type GetAllBooksHandlerFunc func(GetAllBooksParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetAllBooksHandlerFunc) Handle(params GetAllBooksParams) middleware.Responder {
	return fn(params)
}

// GetAllBooksHandler interface for that can handle valid get all books params
type GetAllBooksHandler interface {
	Handle(GetAllBooksParams) middleware.Responder
}

// NewGetAllBooks creates a new http.Handler for the get all books operation
func NewGetAllBooks(ctx *middleware.Context, handler GetAllBooksHandler) *GetAllBooks {
	return &GetAllBooks{Context: ctx, Handler: handler}
}

/*GetAllBooks swagger:route GET /books book getAllBooks

get all books from store

retun all available books in store


*/
type GetAllBooks struct {
	Context *middleware.Context
	Handler GetAllBooksHandler
}

func (o *GetAllBooks) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetAllBooksParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
