// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Store store
// swagger:model Store
type Store struct {

	// id
	// Read Only: true
	ID string `json:"id,omitempty"`

	// store name
	// Required: true
	StoreName *string `json:"storeName"`
}

// Validate validates this store
func (m *Store) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateStoreName(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Store) validateStoreName(formats strfmt.Registry) error {

	if err := validate.Required("storeName", "body", m.StoreName); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Store) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Store) UnmarshalBinary(b []byte) error {
	var res Store
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
